import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";


// Fonts
const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto",
})

const fwc2026 = localFont({
  src: "./fonts/FWC2026.ttf",
  variable: "--font-fwc2026",
  display: "swap",
})

const fifa26 = localFont ({
  src: "./fonts/fifa-26.ttf",
  variable: "--font-fifa-26",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Fifa World Cup 2026",
  description: "Generated by Warlock-Tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${notoSans.variable} ${fwc2026.variable} ${fifa26.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
